server:
  port: 2020

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: certification-service
          uri: lb://certification-service
          predicates:
            - Path=/certification/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
  instance:
    preferIpAddress: true
    ip-address: 210.114.22.192
